version: '3.8'

services:
  sentinai-core:
    build: .
    container_name: sentinai_production
    ports:
      - "5000:5000"
    #volumes:
      # This maps your local code to the container so you don't have to rebuild it every time you change a line of Python!
      #- .:/app
    environment:
      - PYTHONUNBUFFERED=1